version: "3.7"

services:
  database_ignite:
    container_name: container-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=leticia
      - POSTGRES_PASSWORD=ignite
      - POSTGRESS_DB=postgres
    volumes:
      - pgdata/data/postgres 
  app:
    build: .
    container_name: container-rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite
volumes:
  pgdata:
    driver: local